name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pytest grpcio-tools
    
    - name: Build and test
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: ./scripts/build.sh
    
    # Just build the package
    - name: Build package
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python -m build
        echo "Package built successfully. Distribution files are in the dist/ directory."
        ls -la dist/
